FROM docker.io/rabbitmq:3-management

MAINTAINER pymonger "pymonger@gmail.com"
LABEL description="RabbitMQ image for HySDS"

# update configs
COPY hysds-dockerfiles/configs/rabbitmq.config /etc/rabbitmq/rabbitmq.config
COPY hysds-dockerfiles/configs/rabbitmq-server /etc/default/rabbitmq-server
