FROM hysds/pge-base:latest

# provision PGE here, e.g.
# COPY ariamh /root/ariamh

# set entrypoint
USER ops
WORKDIR /root
COPY configs/pge-docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/bin/bash", "--login"]
