FROM hysds/pge-base:latest

# provision dumby PGE
 COPY dumby /root/verdi/ops/dumby
RUN set -ex \
 && yum update -y \
 && yum install -y ImageMagick \
 && yum clean all

# set entrypoint
USER root
WORKDIR /root
COPY configs/pge-docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/bin/bash", "--login"]
