version: 2.1
jobs:
  build:
    docker:
      - image: docker:18.09-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              python-dev py-pip bash pigz build-base libffi-dev openssl-dev
            pip install \
              docker-compose awscli
      - run:
          name: Build
          command: |
            echo "GIT_OAUTH_TOKEN=${GIT_OAUTH_TOKEN}" > $HOME/.git_oauth_token
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./build_develop.sh hysds ${CIRCLE_BRANCH}
      - persist_to_workspace:
          root: images
          paths:
            - "*"
  build-periodically:
    docker:
      - image: docker:18.09-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              python-dev py-pip bash pigz build-base libffi-dev openssl-dev
            pip install \
              docker-compose awscli
      - run:
          name: Build
          command: |
            echo "GIT_OAUTH_TOKEN=${GIT_OAUTH_TOKEN}" > $HOME/.git_oauth_token
            TAG=$(date -u +%Y%m%d)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./rebuild_periodically.sh $TAG weekly hysds master
      - persist_to_workspace:
          root: images
          paths:
            - "*"
  deploy:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              curl file
      - attach_workspace:
          at: images
      - run:
          name: Deploy
          command: |
            cd images
            owner=$CIRCLE_PROJECT_USERNAME
            repo=$CIRCLE_PROJECT_REPONAME
            release_id=$(curl -s -H "Authorization: token $GIT_OAUTH_TOKEN" \
              "https://api.github.com/repos/${owner}/${repo}/releases/latest" \
              | grep '^  "id":' | awk '{print $2}' | sed 's/,//')
            file=hysds-verdi-${CIRCLE_BRANCH}.tar.gz
            curl -H "Authorization: token $GIT_OAUTH_TOKEN" -H \
              "Content-type: $(file -b --mime-type ${file})" \
              --data-binary @${file} \
              "https://uploads.github.com/repos/${owner}/${repo}/releases/${release_id}/assets?name=${file}"
            file=docker-registry-2.tar.gz
            curl -H "Authorization: token $GIT_OAUTH_TOKEN" -H \
              "Content-type: $(file -b --mime-type ${file})" \
              --data-binary @${file} \
              "https://uploads.github.com/repos/${owner}/${repo}/releases/${release_id}/assets?name=${file}"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
  weekly:
    triggers:
      - schedule:
          cron: "0 7 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-periodically:
          filters:
            branches:
              only: master
