version: 2.1
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip bash pigz
            pip install \
              docker-compose awscli
      - run:
          name: Build
          command: |
            TAG=$(date -u +%Y%m%d)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./rebuild_all.sh $TAG hysds master
      - persist_to_workspace:
          root: images
          paths:
            - "*"
  build-periodically:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip bash pigz
            pip install \
              docker-compose awscli
      - run:
          name: Build
          command: |
            TAG=$(date -u +%Y%m%d)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./rebuild_periodically.sh $TAG weekly hysds master
      - persist_to_workspace:
          root: images
          paths:
            - "*"
  deploy:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              curl file
      - attach_workspace:
          at: images
      - run:
          name: Deploy
          command: |
            cd images
            owner=hysds
            repo=hysds-dockerfiles
            release_id=$(curl -s -H "Authorization: token $GIT_OAUTH_TOKEN" \
              "https://api.github.com/repos/${owner}/${repo}/releases/latest" \
              | grep '^  "id":' | awk '{print $2}' | sed 's/,//')
            file=hysds-verdi-latest.tar.gz
            curl -H "Authorization: token $GIT_OAUTH_TOKEN" -H \
              "Content-type: $(file -b --mime-type ${file})" \
              --data-binary @${file} \
              "https://uploads.github.com/repos/${owner}/${repo}/releases/${release_id}/assets?name=${file}"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  weekly:
    triggers:
      - schedule:
          cron: "0 7 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-periodically:
          filters:
            branches:
              only: master
