version: 2.1
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            pwd
            ls -al
            sh rebuild_all.sh $(date -u +%Y%m%d)
