version: 2.1
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip bash
            pip install \
              docker-compose awscli
      - run:
          name: Build
          command: |
            TAG=$(date -u +%Y%m%d)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./rebuild_all.sh $TAG

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      #- deploy:
      #    requires:
      #      - build
      #    filters:
      #      branches:
      #        only: master
