version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: pwd
          command: |
            pwd
      - run:
          name: ls
          command: |
            ls -al
      - run:
          name: Build
          command: |
            ./rebuild_all.sh $(date -u +%Y%m%d)
