version: '2.2'
services:
  verdi:
    hostname: verdi
    container_name: verdi
    image: hysds/verdi
    init: true
    user: "${HOST_UID}:${HOST_GID}"
    environment:
      - AWS_METADATA_SERVICE_TIMEOUT=5
      - AWS_METADATA_SERVICE_NUM_ATTEMPTS=5
      - HYSDS_HOME=${HYSDS_HOME}
      - HOST_USER=$(whoami)
    ports:
      - "8085:8085"
      - "9001:9001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DATA_DIR}/work:/data/work"
      - "${HYSDS_HOME}:${HYSDS_HOME}"
      - "${HYSDS_HOME}/verdi/etc:${HYSDS_HOME}/verdi/etc"
      - "${HYSDS_HOME}/verdi/log:${HYSDS_HOME}/verdi/log"
      - "${HYSDS_HOME}/verdi/etc/celeryconfig.py:/root/verdi/etc/celeryconfig.py"
      - "${HOME}/.aws:/root/.aws"
      - "${HOME}/.boto:/root/.boto"
      - "${HOME}/.s3cfg:/root/.s3cfg"
      - "${HOME}/.netrc:/root/.netrc"
    command: ["bash", "-c", "supervisord -n -c ${HYSDS_HOME}/verdi/etc/supervisord.conf"]
